version: 0.2

env:
  variables:
    AWS_DEFAULT_REGION: eu-central-1

phases:

  install:
    runtime-versions:
      nodejs: latest
    commands:
      # needed by Cypress
      - apt-get install -y libgtk2.0-0 libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 xvfb
      - npm install

  pre_build:
    commands:
      # switching role for deploy
      - ASSUME_ROLE_ARN="arn:aws:iam::$account_id:role/AccessBgdiS3"
      - TEMP_ROLE=`aws sts assume-role --role-arn $ASSUME_ROLE_ARN --role-session-name test`
      - export TEMP_ROLE
      - echo $TEMP_ROLE
      - export AWS_ACCESS_KEY_ID=$(echo "${TEMP_ROLE}" | jq -r '.Credentials.AccessKeyId')
      - export AWS_SECRET_ACCESS_KEY=$(echo "${TEMP_ROLE}" | jq -r '.Credentials.SecretAccessKey')
      - export AWS_SESSION_TOKEN=$(echo "${TEMP_ROLE}" | jq -r '.Credentials.SessionToken')
      - echo $AWS_ACCESS_KEY_ID
      - echo $AWS_SECRET_ACCESS_KEY
      - echo $AWS_SESSION_TOKEN

  build:
    commands:
      # will build the application in dev mode before testing
      - npm run test:headless

  post_build:
    commands:
      # will build the application in development mode before deploying
      - npm run deploy:dev AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID --build-arg AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY --build-arg AWS_SESSION_TOKEN=$AWS_SESSION_TOKEN
