version: 0.2

env:
  variables:
    AWS_DEFAULT_REGION: eu-central-1

phases:

  install:
    runtime-versions:
      nodejs: latest
    commands:
      # needed by Cypress
      - apt-get install -y libgtk2.0-0 libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 xvfb
      - npm install

  build:
    commands:
      - npm run test:headless
      - npm run build

  post_build:
    commands:
      - echo Build completed on `date`
