version: 0.2

env:
  variables:
    AWS_DEFAULT_REGION: eu-central-1
  parameter-store:
    AWS_SWISSTOPO_BGDI_ACCOUNT_ID: swisstopo-bgdi_account-id

phases:

  install:
    runtime-versions:
      nodejs: latest
    commands:
      # ensuring we have the latest libs on this Ubuntu
      - apt-get update -y
      # install libs needed by Cypress
      - apt-get install -y libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb
      # ensuring that npm is at the latest version (>= 7.0)
      - npm install -g npm@latest
      # npm ci reads only the package-lock.json file (not the package.json) to be sure to have exactly the same libraries
      # that were used last time npm install was done on the developer's device.
      - npm ci

  build:
    commands:
      # will build the application in dev mode before testing
      - npm run test:ci

  post_build:
    commands:
      # Reading git branch (the utility in the deploy script is unable to read it automatically on CodeBuild)
      # see https://stackoverflow.com/questions/47657423/get-github-git-branch-for-aws-codebuild
      - export CODEBUILD_GIT_BRANCH="$(git symbolic-ref HEAD --short 2>/dev/null)"
      - if [ "$CODEBUILD_GIT_BRANCH" = "" ] ; then
          CODEBUILD_GIT_BRANCH="$(git branch -a --contains HEAD | sed -n 2p | awk '{ printf $1 }')";
          export CODEBUILD_GIT_BRANCH=${CODEBUILD_GIT_BRANCH#remotes/origin/};
        fi
      # if this build has been triggered by a push on master (PR merge on master), we deploy on INT (otherwise everything goes to dev)
      - export CODEBUILD_DEPLOY_TARGET="dev"
      - if [ "$CODEBUILD_GIT_BRANCH" = "master" ] ; then
          export CODEBUILD_DEPLOY_TARGET="int";
        fi
      # switching role for deploy (otherwise the S3 bucket won't be visible as it's another account)
      # the application will be built by the npm target before deploying
      - npm run deploy:$CODEBUILD_DEPLOY_TARGET -- --role=arn:aws:iam::$AWS_SWISSTOPO_BGDI_ACCOUNT_ID:role/BgdiCodebuildAccess --branch=$CODEBUILD_GIT_BRANCH
