version: 0.2

env:
  variables:
    AWS_DEFAULT_REGION: eu-central-1

phases:

  install:
    runtime-versions:
      nodejs: latest
    commands:
      # needed by Cypress
      - apt-get install -y libgtk2.0-0 libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 xvfb
      - npm install

  build:
    commands:
      # will build the application in dev mode before testing
      - npm run test:headless

  post_build:
    commands:
      # will build the application in production mode before deploying
      - npm run deploy:int
