name: Create test link on PR creation
on:
  pull_request:
    types: [opened]
jobs:
  update_pr:
    runs-on: ubuntu-latest
    steps:
      - uses: tzkhan/pr-update-action@v2
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          head-branch-regex: '.+'
          body-template: |

            [Test link](https://web-mapviewer.dev.bgdi.ch/%headbranch%/index.html)
          body-update-action: 'suffix'
          body-uppercase-head-match: false
